version: '3'

services:

  nginx1:
    build: ./nginx1
    ports:
      - "8081:80"
    depends_on:
      - php1
    volumes:
      - /php_nginx_1:/var/www/html

  nginx2:
    build: ./nginx2
    ports:
      - "8082:80"
    depends_on:
      - php2
    volumes:
      - /php_nginx_2:/var/www/html

  php1:
    build: ./php1
    depends_on:
      - db
    volumes:
      - /php_nginx_1:/var/www/html

  php2:
    build: ./php2
    depends_on:
      - db
    volumes:
      - /php_nginx_2:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password

