version: '3'

services:

  nginx1:
    build: ./nginx1
    ports:
      - "8081:80"
    depends_on:
      - php1
    volumes:
      - /php_nginx_1:/var/www/html

  nginx2:
    build: ./nginx2
    ports:
      - "8082:80"
    depends_on:
      - php2
    volumes:
      - /php_nginx_2:/var/www/html

  php1:
    build: ./php1
    depends_on:
      - mysql 
    volumes:
      - /php_nginx_1:/var/www/html

  php2:
    build: ./php2
    depends_on:
      - mysql 
    volumes:
      - /php_nginx_2:/var/www/html
 
  mysql:
   image: mysql:latest
   environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_username
      MYSQL_PASSWORD: your_database_password
   ports:
      - 3306:3306
